-- AlterTable
ALTER TABLE `assets` MODIFY `entityType` ENUM('PRODUCT', 'PROFILE', 'ORDER', 'INVOICE', 'BANNER', 'LOGO', 'CATEGORY', 'BRAND', 'CUSTOMER', 'SELLER', 'PTYPE', 'SUPPLIERS', 'CARRIER', 'GALLERY', 'OTHER') NOT NULL;
